name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:v0.24.5
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    strategy:
      matrix:
        sample: [cylock/tests/base2]
        target: [nrf52dk_nrf52832]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: nader

      - name: Set variables
        working-directory: nader
        id: vars
        run: |
             echo "::set-output name=branch::${GITHUB_REF#refs/*/}"
             echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Initialize
        working-directory: nader
        run: |
          pip3 install -U west
          west init -l .
          west update
          pip3 install -r ../zephyr/scripts/requirements-base.txt

      - name: Build ${{ matrix.sample }} for ${{ matrix.target }}
        working-directory: nader
        run: |
          west build -b ${{ matrix.target }} -s ${{ matrix.sample }} -p
          #mkdir -p .out
          #cp build/zephyr/app_update.bin .out/${{ matrix.sample }}_${{ matrix.target }}_app_update.bin
          #cp build/zephyr/merged.hex .out/${{ matrix.sample }}_${{ matrix.target }}_merged.hex


      - name: Create build tarball
        working-directory: nader
        run: |
          cd build/zephyr
          tar czf build.tar.gz zephyr.hex

    #  - name: Archive firmware
    #    uses: actions/upload-artifact@v3
    #    with:
    #      name: nfed_${{ steps.vars.outputs.branch }}_${{ steps.vars.outputs.sha_short }}
    #      path: nader/.out/
          
      - name: Upload tarball
        uses: actions/upload-artifact@v3
        with:
          name: build.tar.gz
          path: nader

  hw_flash_and_test:
    needs: build
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: nader

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: nader

      - name: Download build tarball
        uses: actions/download-artifact@v3
        with:
          name: build.tar.gz
          path: nader/

      - name: Untar
        run: |
          tar xvf build.tar.gz
          
      - name: Flash and Verify Test Results
        run: |
          cd $HOME/python
          sudo python3 rtt2.py nRF52832_xxAB  /home/nader/actions-runner/_work/CI-HIL-test/CI-HIL-test/nader/build/zephyr/zephyr.hex
