name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:v0.24.5
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    strategy:
      matrix:
        sample: [cylock]
        target: [nrf52dk_nrf52832]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: nader

      - name: Set variables
        working-directory: nader
        id: vars
        run: |
             echo "::set-output name=branch::${GITHUB_REF#refs/*/}"
             echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Initialize
        working-directory: nader
        run: |
          pip3 install -U west
          west init -l .
          west update
          pip3 install -r ../zephyr/scripts/requirements-base.txt

      - name: Build ${{ matrix.sample }} for ${{ matrix.target }}
        working-directory: nader
        run: |
          west build -b ${{ matrix.target }} -s ${{ matrix.sample }} -p
          mkdir -p .out
          cp build/zephyr/app_update.bin .out/${{ matrix.sample }}_${{ matrix.target }}_app_update.bin
          cp build/zephyr/merged.hex .out/${{ matrix.sample }}_${{ matrix.target }}_merged.hex
          tar czf build.tar.gz build/zephyr/merged.hex


      - name: Archive firmware
        uses: actions/upload-artifact@v3
        with:
          name: nfed_${{ steps.vars.outputs.branch }}_${{ steps.vars.outputs.sha_short }}
          path: nader/.out/
          
      - name: Upload tarball
        uses: actions/upload-artifact@v2
        with:
          name: build.tar.gz
          path: nader/test/build.tar.gz

  hw_flash_and_test:
    needs: build
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: connection_tests

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: connection_tests

      - name: Download build tarball
        uses: actions/download-artifact@v2
        with:
          name: build.tar.gz
          path: connection_tests/test/build.tar.gz

      - name: Untar
        run: |
          cd test
          tar xvf build.tar.gz
          
      - name: Flash and Verify Test Results
        run: |
          cd $HOME/python
          python3 rtt3.py

